[package]
name = "ex_secp256k1"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "ex_secp256k1"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.27"
libsecp256k1 = "0.7.1"
